package com.android.portguard.ui.state

data class DiagnosticsUiState(
    val loading: Boolean = false,
    val rootGranted: Boolean = false,
    val moduleInstalled: Boolean = false,
    val settingsFound: Boolean = false,
    val stateDirFound: Boolean = false,
    val configFound: Boolean = false,
    val statusFileFound: Boolean = false,
    val summaryFileFound: Boolean = false,
    val incidentsFileFound: Boolean = false,
    val configJsonValid: Boolean = false,
    val statusJsonValid: Boolean = false,
    val summaryJsonValid: Boolean = false,
    val appVersionName: String = "",
    val appVersionCode: Int = 0,
    val androidVersionText: String = "",
    val installerLabel: String = "",
    val assetPresent: Boolean = false,
    val moduleVersionName: String = "",
    val moduleVersionCode: String = "",
    val statusText: String = "",
    val infoMessage: String? = null,
    val errorMessage: String? = null,
    val modulePath: String = "",
    val settingsPath: String = "",
    val statePath: String = "",
    val configPreview: String = "",
    val statusPreview: String = "",
    val summaryPreview: String = "",
    val incidentsPreview: String = "",
)
